# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9a0eebe8efd0944758bf723026e26928cc5449e6d16d291bceaab17020b3b2263c8fc843b6d0500de0f829b1cba02c4043c03747c61ea5cdaef2543427038e

test:
  secret_key_base: 6391fbebb8d289eccdd8dae082b86f84902dc4ca5072d3d5bb8cb2f4206c8bd2f06dac28e876683e639a41c1f48bb9dc42cb6fe72d33f6116b6d66d44b1f59ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
